name: hackathon-mia10
services:
  hackathon-mia10:
    container_name: hackathon-mia10
    restart: always
    build:
      context: ./webapp
    environment:
      - HOST=0.0.0.0
      - PORT=3333
      - LOG_LEVEL=info
      - APP_KEY=1LX44LT48f7sdf4KCUJpQG9g7IM
      - NODE_ENV=production
      - SESSION_DRIVER=cookie
    ports:
      - 3333:3333

  api:
    container_name: api-python
    restart: always
    build:
      context: ./Api
    environment:
      - FLASK_APP
    ports:
      - 5000:5000
